/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;



import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;


import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import onetwocar.CallBackResuil;
import onetwocar.CallBackResuilBrand;
import onetwocar.FeedBrand;
import onetwocar.FeedData;
import model.BrandModel;
import unseencar.FeedBrandUnSeen;

/**
 *
 * @author humnoy
 */
public class MainFrame extends javax.swing.JFrame {

    private int start = 1;
    private int end = 1;
    private List<BrandModel> BrandModel;
    private String brand_valuse = "";
    private List<String> list;
    
    public MainFrame() {
        initComponents();
        intiListData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_Brand = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        lbl_pageCount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        input_start = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input_end = new javax.swing.JTextField();
        ButtonStart = new javax.swing.JButton();
        lbl_Status = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();
        ProgressBar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton_One2Car = new javax.swing.JRadioButton();
        jRadioButton_UnSeenCar = new javax.swing.JRadioButton();
        jButton_Load = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Feed Data v.1.1 By Humnoy Developer");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Brands", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14), javax.swing.UIManager.getDefaults().getColor("CheckBox.disabledText"))); // NOI18N

        List_Brand.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        List_Brand.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        List_Brand.setToolTipText("คลิกเลือก Brand");
        List_Brand.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                List_BrandValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(List_Brand);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Page"));

        lbl_pageCount.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_pageCount.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.select"));
        lbl_pageCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pageCount.setText("Number Page");
        lbl_pageCount.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pageCount, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_pageCount, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Feed Data"));

        input_start.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        input_start.setToolTipText("");
        input_start.setEnabled(false);
        input_start.setPreferredSize(new java.awt.Dimension(70, 29));
        input_start.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_startKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Start");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("End");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        input_end.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        input_end.setToolTipText("");
        input_end.setEnabled(false);
        input_end.setPreferredSize(new java.awt.Dimension(70, 29));
        input_end.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_endKeyReleased(evt);
            }
        });

        ButtonStart.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        ButtonStart.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.select"));
        ButtonStart.setText("START");
        ButtonStart.setEnabled(false);
        ButtonStart.setName(""); // NOI18N
        ButtonStart.setPreferredSize(new java.awt.Dimension(87, 30));
        ButtonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonStartMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(input_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(input_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(ButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        lbl_Status.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        lbl_Status.setForeground(java.awt.Color.red);
        lbl_Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Status.setText("Loading...");
        lbl_Status.setToolTipText("");

        TableData.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableData.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        TableData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TableData.setRowHeight(27);
        TableData.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(TableData);

        ProgressBar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ProgressBar.setForeground(new java.awt.Color(51, 51, 255));
        ProgressBar.setToolTipText("");
        ProgressBar.setPreferredSize(new java.awt.Dimension(146, 50));
        ProgressBar.setSize(new java.awt.Dimension(146, 50));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Feed Data V.1.1");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRadioButton_One2Car.setSelected(true);
        jRadioButton_One2Car.setText("One2Car");

        jRadioButton_UnSeenCar.setText("UnSeenCar");

        jButton_Load.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton_Load.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButton_Load.setText("Load");
        jButton_Load.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton_LoadMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_One2Car)
                    .addComponent(jRadioButton_UnSeenCar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton_Load, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton_One2Car)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_UnSeenCar)
                .addGap(18, 18, 18)
                .addComponent(jButton_Load, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(512, 512, 512))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 100, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonStartMouseClicked
        // TODO add your handling code here:
        if(!ButtonStart.isEnabled()) return;
                
        lbl_Status.setText("Loading...");
        new FeedData(start, end, brand_valuse, new CallBackResuil() {
            @Override
            public void onStart() {
                ProgressBar.setValue(0);
            }

            @Override
            public void onProgressBar(int size, int i) {
                lbl_Status.setText("Loading:"+i);
                ProgressBar.setValue(((i*100)/size)+1);
            }
                @Override
                public void succeed(List<String> data, String pagerView) {
                    lbl_pageCount.setText(pagerView);
                    addDataTable(data);
                    lbl_Status.setText("Succeed!!");
                }
            }).execute();

        
            
          
    }//GEN-LAST:event_ButtonStartMouseClicked

    private void input_startKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_startKeyReleased
        // TODO add your handling code here:
//        lbl_Status.setText("");
         if(!input_start.getText().equals("")){
             try {
                 start = Integer.valueOf(input_start.getText());
             } catch (NumberFormatException e) {
                 input_end.setEnabled(false);
                 ButtonStart.setEnabled(false);
                 return;
             }
             input_end.setEnabled(true);
             ButtonStart.setEnabled(true);
        }else{
             input_end.setEnabled(false);
             ButtonStart.setEnabled(false);
         }
              
    }//GEN-LAST:event_input_startKeyReleased

    private void input_endKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_endKeyReleased
        // TODO add your handling code here:
//        lbl_Status.setText("");
        if(!input_end.getText().equals("")){
             try {
                 end = Integer.valueOf(input_end.getText());
             } catch (NumberFormatException e) {
                 ButtonStart.setEnabled(false);
                 return;
             }
             ButtonStart.setEnabled(true);
            
        }else{
             ButtonStart.setEnabled(false);
         }
        
                
        
    }//GEN-LAST:event_input_endKeyReleased

    private void List_BrandValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_List_BrandValueChanged
        if(!evt.getValueIsAdjusting()){
                input_start.setEnabled(true);
                brand_valuse = BrandModel.get(List_Brand.getSelectedIndex()-1).getValuse();
             
                new FeedData(start, end, brand_valuse, new CallBackResuil() {
                    @Override
            public void onStart() {
                 lbl_Status.setText("Loading...");
                ProgressBar.setValue(0);
            }

            @Override
            public void onProgressBar(int size, int i) {
                ProgressBar.setValue(((i*100)/size)+1);
            }
                @Override
                public void succeed(List<String> data, String pagerView) {
                    lbl_pageCount.setText(pagerView);
                    addDataTable(data);
                    lbl_Status.setText("Succeed!!");
                }
            }).execute();


     
        }
        
    }//GEN-LAST:event_List_BrandValueChanged

    private void jButton_LoadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoadMouseReleased
           if (jRadioButton_One2Car.isSelected()) {
                lbl_Status.setText("Loading...");
            new FeedBrand(new CallBackResuilBrand() {
                @Override
                public void onStart() {
                    ProgressBar.setValue(0);
                }

                @Override
                public void onProgressBar(int size, int i) {
                    ProgressBar.setValue(((i * 100) / size) + 1);
                }

                @Override
                public void succeed(String[] obj_list_brand, List<BrandModel> brandModels) {
                    List_Brand.setListData(obj_list_brand);
                    BrandModel = brandModels;
                    lbl_Status.setText("Succed!!");
                }
            }).execute();

        }
            
            if(jRadioButton_UnSeenCar.isSelected()){
                
//                new FeedBrandUnSeen(new CallBackResuilBrand() {
//                    @Override
//                    public void onStart() {
//                         ProgressBar.setValue(0);
//                    }
//
//                    @Override
//                    public void onProgressBar(int size, int i) {
//                       ProgressBar.setValue(((i * 100) / size) + 1);
//                    }
//
//                    @Override
//                    public void succeed(String[] obj_list_brand, List<BrandModel> brandModels) {
//                        BrandModel = brandModels;
//                        lbl_Status.setText("Succed!!");
//                        obj_list_brand = new String[brandModels.size()];
//                        for(int i =0 ; i < obj_list_brand.length;i++){
//                        obj_list_brand[i] = brandModels.get(i).getBrang();
//                                }
//                    }
//                }).execute();
                
                
            }
      
        
    }//GEN-LAST:event_jButton_LoadMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonStart;
    private javax.swing.JList<String> List_Brand;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JTable TableData;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField input_end;
    private javax.swing.JTextField input_start;
    private javax.swing.JButton jButton_Load;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton_One2Car;
    private javax.swing.JRadioButton jRadioButton_UnSeenCar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Status;
    private javax.swing.JLabel lbl_pageCount;
    // End of variables declaration//GEN-END:variables

    private void intiListData() {
        TableData.getColumnModel().getColumn(0).setPreferredWidth(20);
        TableData.getColumnModel().getColumn(1).setPreferredWidth(280);
        TableData.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.LEFT );
        TableData.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        
        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButton_One2Car);
        group.add(jRadioButton_UnSeenCar);
     
    
    }
    
    private void addDataTable(List<String> data){
        DefaultTableModel model = (DefaultTableModel) TableData.getModel();
        
//         Collections.sort(data,new Comparator<String>(){
//            @Override
//            public int compare(String o1, String o2) {
//                return o1.compareToIgnoreCase(o2);
//            }
//    });
        
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
            model.removeRow(i);
            }
        }   
        for(int i=0;i <= data.size()-1; i++){
            model.addRow(new Object[0]);
		model.setValueAt(i+1, i, 0);
		model.setValueAt(data.get(i), i, 1);	
  	}
    }
    
   
}
